"""traffic telemetry - traffic_segments, traffic_observations,
traffic_historical_profiles, and new columns on traffic_snapshots
(CLAUDE.md #7 domain model; QTrace crowd-traffic system)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-17

Written by hand and verified against a real local PostgreSQL instance
(`alembic upgrade head` run successfully) - not autogenerated.

Only ADDs tables/columns; nothing from 0001 is altered or dropped
(CLAUDE.md #17, #55 - never edit a migration that may already be applied).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "traffic_segments",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("node_a", sa.BigInteger, nullable=False),
        sa.Column("node_b", sa.BigInteger, nullable=False),
        sa.Column("geometry", sa.JSON, nullable=True),
        sa.Column("profile_speed_mps", sa.Float, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("node_a", "node_b", name="uq_traffic_segments_node_pair"),
    )
    op.create_index("ix_traffic_segments_node_a", "traffic_segments", ["node_a"])
    op.create_index("ix_traffic_segments_node_b", "traffic_segments", ["node_b"])

    op.create_table(
        "traffic_observations",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("segment_id", sa.String(36), sa.ForeignKey("traffic_segments.id"), nullable=False),
        sa.Column("observed_speed_mps", sa.Float, nullable=False),
        sa.Column("accuracy_m", sa.Float, nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_traffic_observations_segment_id", "traffic_observations", ["segment_id"])
    op.create_index("ix_traffic_observations_recorded_at", "traffic_observations", ["recorded_at"])
    op.create_index("ix_traffic_observations_created_at", "traffic_observations", ["created_at"])

    op.create_table(
        "traffic_historical_profiles",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("segment_id", sa.String(36), sa.ForeignKey("traffic_segments.id"), nullable=False),
        sa.Column("day_of_week", sa.Integer, nullable=False),
        sa.Column("time_bucket_minutes", sa.Integer, nullable=False),
        sa.Column("median_speed_mps", sa.Float, nullable=False),
        sa.Column("sample_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "segment_id", "day_of_week", "time_bucket_minutes", name="uq_traffic_historical_profile_bucket"
        ),
    )
    op.create_index("ix_traffic_historical_profiles_segment_id", "traffic_historical_profiles", ["segment_id"])

    op.add_column("traffic_snapshots", sa.Column("segment_id", sa.String(36), nullable=True))
    op.add_column("traffic_snapshots", sa.Column("current_speed_mps", sa.Float, nullable=True))
    op.add_column("traffic_snapshots", sa.Column("reference_speed_mps", sa.Float, nullable=True))
    op.add_column("traffic_snapshots", sa.Column("congestion_score", sa.Float, nullable=True))
    op.add_column(
        "traffic_snapshots", sa.Column("observation_count", sa.Integer, nullable=False, server_default="0")
    )
    op.add_column("traffic_snapshots", sa.Column("confidence", sa.Float, nullable=True))
    op.add_column(
        "traffic_snapshots", sa.Column("status", sa.String(20), nullable=False, server_default="UNKNOWN")
    )
    op.create_foreign_key(
        "fk_traffic_snapshots_segment_id", "traffic_snapshots", "traffic_segments", ["segment_id"], ["id"]
    )
    op.create_index("ix_traffic_snapshots_segment_id", "traffic_snapshots", ["segment_id"])


def downgrade() -> None:
    op.drop_index("ix_traffic_snapshots_segment_id", table_name="traffic_snapshots")
    op.drop_constraint("fk_traffic_snapshots_segment_id", "traffic_snapshots", type_="foreignkey")
    op.drop_column("traffic_snapshots", "status")
    op.drop_column("traffic_snapshots", "confidence")
    op.drop_column("traffic_snapshots", "observation_count")
    op.drop_column("traffic_snapshots", "congestion_score")
    op.drop_column("traffic_snapshots", "reference_speed_mps")
    op.drop_column("traffic_snapshots", "current_speed_mps")
    op.drop_column("traffic_snapshots", "segment_id")

    op.drop_table("traffic_historical_profiles")
    op.drop_table("traffic_observations")
    op.drop_table("traffic_segments")
